### ISSUE TITLE
Error Building Wheel for krec on Windows with WSL

### ISSUE THREAD

**Issue by mdrazak2001** [kscalelabs/krec#5]
`I am encountering an error while trying to build the wheel for the `krec` package on Windows using WSL. The error message is as follows:`

Building wheels for collected packages: krec Running command Building wheel for krec (pyproject.toml) running bdist_wheel running build running build_py running build_ext error: [WinError 2] The system cannot find the file specified error: subprocess-exited-with-error

× Building wheel for krec (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip. full command: 'C:\Users\moham\Projects\store\store\venv\Scripts\python.exe' 'C:\Users\moham\Projects\store\store\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\in_process.py' build_wheel 'C:\Users\moham\AppData\Local\Temp\tmpf29edqi' cwd: C:\Users\moham\AppData\Local\Temp\pip-install-zw9puqak\krec_0a8e3f30834d48ca842cb29675c1434c Building wheel for krec (pyproject.toml) ... error ERROR: Failed building wheel for krec Failed to build krec ERROR: ERROR: Failed to build installable wheels for some pyproject.tomlbased projects (krec)

` I have ensured that protoc is installed and included in my PATH. I have also referred to the [official documentation](https://docs.kscale.dev/models/krec) but the issue persists. `

Any guidance on resolving this issue would be greatly appreciated.

**Comment by codekansas** [comment]
we do not support windows unfortunately :(
